language: csharp
solution: PantMerchantWin.sln
script:
  - xbuild PantMerchantWin.sln
  # - mono packages/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe Tests/Tests.csproj

notifications:
  email: false